Fix responsive design
githansen/bachelor_frontend pull request #55
Opened 2023-02-15 14:23 UTC by junus-sefa

2023-02-15 16:32 UTC, tonystr requested changes
Diverse bugs som må fikses før vi merger. Ellers bra jobbet 👍

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/Reader.jsx
> +                }}
Jeg synes denne animasjonen er litt for mye. Kan se bra ut hvis den brukes bare når bruker ber om en ny tekst, men det føles litt kvalmende ut når spiller av når bruker går inn i siden

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/Reader.jsx
> +                }}
Kanskje det fungerer med lavere y offsett

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/Reader.jsx
> +import userReadingProgress from '@/hooks/userReadingProgress';
userReadingProgress burde hete useReadingProgress (alle react hooks skal starte med "use")

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/Thanks.jsx
> +                    <m.img //React library
Tror ikke denne kommentaren hører hjemme her? Burde ikke bruke js kommentarer i jsx markup heller (bruk {/* kommentar */} istedenfor)

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/controls/CompletedControls.jsx
> +                                displayAudioPlayer === true ? 'block' : 'hidden'
trenger ikke `=== true` når displayAudioPlayer altid er en boolean, bruk `displayAudioPlayer ? 'block' : 'hidden'`

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/controls/CompletedControls.jsx
> +                                displayAudioPlayer === true ? 'hidden' : 'block'
trenger ikke `=== true` når displayAudioPlayer altid er en boolean, bruk `displayAudioPlayer ? 'hidden' : 'block'`

2023-02-15 16:32 UTC, tonystr commented on src/pages/additional/DeleteRecording.jsx
> +                                    onKeyPress={(event) => {
`event` er et reservert nøkkelord i javascript, dette kan lede til problemer. Bruk `e`, `evt`, eller andre navn istedenfor

2023-02-15 16:32 UTC, tonystr commented on src/pages/additional/DeleteRecording.jsx
> +                                        if (!/[0-9]/.test(event.key)) {
UUID består av hexadesimal verdier, så korrekt regex vil være /^[0-9a-fA-F]+$/. Pass på at dette fortsatt støtter backspace, delete og navigering med piltastene

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/controls/CompletedControls.jsx
> +                                    stroke-width="4"
`stroke-width` er ikke valid i react kode. Enten må svgen flyttes til sin egen fil og imporeres, eller så må `stroke-width` endres til `strokeWidth`

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/controls/CompletedControls.jsx
> +                                    stroke-width="4"
`class` er heller ikke valid react kode, disse (3 steder) må endres til `className` om du velger å ha svg kode inline i react kode

2023-02-15 16:32 UTC, tonystr commented on src/pages/Reader/controls/CompletedControls.jsx
> +                                    stroke-width="4"
dette problemet oppstår også i DeleteRecording.jsx linjer 241-256 for `stroke-linejoin`, `stroke-width` og `stroke-linecap`

2023-02-15 16:59 UTC, junus-sefa commented on src/pages/Reader/Reader.jsx
> +                }}
Fjerner bevegelse, og legger heller til animasjon ved gjennomsiktighet.

2023-02-17 20:49 UTC, tonystr approved these changes

2023-02-17 20:50 UTC, merged