Implementering av Admin side for Gi Din Stemme
githansen/bachelor_frontend pull request #65
Opened 2023-02-27 14:02 UTC by junus-sefa

2023-02-27 17:58 UTC, tonystr requested changes
Har ikke sett igjennom alle filene, kommer sannsynligvis med flere kommentarer imorgen

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/chart/ChartUserAge.jsx
> +}
Vi vil helst unngå å bruke class-based components med mindre det er veldig vanskelig å unngå. Her er det lett å konvertere til function component:

```jsx
function ChartUserAge() {
    const options = {...};
    const series = [...];
    
    return (
            <div className="app">
                <div className="row">
                    <div className="mixed-chart">
                        <Chart
                            options={options}
                            series={series}
                            type="polarArea"
                            height="450px"
                            width="100%"
                        />
                    </div>
                </div>
            </div>
    );
}
```

Det er heller ingen grunn for å large series og options i state, når dataen aldri skal endres inne i dette Componentet. I fremtiden kommmer vi til å enten passe dataen inn gjennom props, eller gjøre api requests istedenfor å definere dataen her.

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/chart/ChartUserDialect.jsx
> +class ChartUserDialect extends Component {
Bruk function component her også

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/chart/ChartUserGender.jsx
> +class ChartUserGender extends React.Component {
Bruk function component her også

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/chart/ChartUsersPerDay.jsx
> +class ChartUsersPerDay extends Component {
Bruk function component her også

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/shared/DashMenu.jsx
> +            path: '/gdsadmin/',
kan vi rename til bare admin?

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/shared/DashMenu.jsx
> +                    !open && 'rotate-180'
dette burde være en ternary som returnerer en tom streng hvis open er true, ellers vil den legge til en klasse som heter "false"

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/shared/DashMenu.jsx
> +                        !open && 'scale-0'
bruk ternary her også

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/shared/DashMenu.jsx
> +                            <div className={`font-fet ${!open && 'hidden'}`}>
bruk ternary her også

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/table/ContributionTable.jsx
> +    //
tomme kommentarer?

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/table/ContributionTable.jsx
> +                                        </>
hvorfor bruker vi <></> her? Det virker hennsiktsløst, kan få mer leselig kode med å fjerne dem og paranteser (altså bare `return <Component className="h-5 w-5" />;`)

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/table/StandardTable.jsx
> +                                        </>
samme kommentar om  <></>

2023-02-27 17:58 UTC, tonystr commented on src/dashboard/components/table/ContributionTable.jsx
> +                                                                    event.target
bruk `e` istedenfor order `event`. `event` er et reservert nøkkelord i javascript, det kan lede til problemer

2023-02-27 20:10 UTC, junus-sefa commented on src/dashboard/components/chart/ChartUserDialect.jsx
> +class ChartUserDialect extends Component {
Done

2023-02-27 20:10 UTC, junus-sefa commented on src/dashboard/components/chart/ChartUserGender.jsx
> +class ChartUserGender extends React.Component {
Done

2023-02-27 20:11 UTC, junus-sefa commented on src/dashboard/components/shared/DashMenu.jsx
> +            path: '/gdsadmin/',
Admin er et generelt navn alle vet om. Så for sikkerhetsgrunner er denne endret til noe litt utenom det normale.

2023-02-27 20:11 UTC, junus-sefa commented on src/dashboard/components/chart/ChartUserAge.jsx
> +}
Done

2023-02-28 10:25 UTC, tonystr requested changes

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/components/table/StandardTable.jsx
> +import toast, { Toaster } from 'react-hot-toast';
trenger ikke å importere Toaster her

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/pages/settings/Settings.jsx
> +import toast, { Toaster } from 'react-hot-toast';
trenger ikke å importere Toaster her

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/components/table/StandardTable.jsx
> +        toast.success('Nullstilling vellykket!');
Dette er ikke en handling som kan feile, så burde bare være `toast('Nullstillt')`

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/components/table/addon/TableHelpers.jsx
> +
denne filen exporterer ikke et react komponent som default, så den burde ikke være navngitt som et komponent. Endre til `tableHelpers.js`

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/components/table/addon/TablePagination.jsx
> +export const Pagination = ({
denne burde exporteres som default function, ikke const: `export default function Pagination({` (husk å fjerne => på linje 16)

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/components/table/addon/TablePagination.jsx
> +/* eslint-disable jsx-a11y/accessible-emoji */
Hvorfor trengs denne kommentaren? Jeg ser ingen emojis i filen. Er det for heroicons?

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/pages/tags/TagCategoriesPage.jsx
> +                    </NavLink>
Ikke bruk NavLink her, bare Link. NavLink er for lenker som vises likt på forskjellige sider

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/pages/tags/TagSingleCategoryPage.jsx
> +    const categoryType = location.state;
her er det best om vi bruker `categoryType = location.state.categoryType;` og setter `state={{ categoryType: value }}` hvor enn det blir satt istedenfor `state={value}`

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/pages/tags/TagSinglePage.jsx
> +    }, [actionType]);
her må categoryType også være en dependency for effekten

2023-02-28 10:25 UTC, tonystr commented on src/dashboard/pages/texts/TextSinglePage.jsx
> +    });
Hvorfor bruker vi en ref her? countWords kalles allerede av onChange. Virker ikke som useEffect eller ref er nødvendig her

2023-03-01 19:06 UTC, junus-sefa commented on src/dashboard/components/table/StandardTable.jsx
> +                                        </>
Done

2023-03-01 19:25 UTC, junus-sefa commented on src/dashboard/pages/texts/TextSinglePage.jsx
> +    });
Ref brukes for å hente input fra inputfelt. useEffect brukes for å oppdatere wordcount når bruker skriver i tekstfelt.

2023-03-02 01:16 UTC, junus-sefa commented on src/dashboard/components/table/addon/TablePagination.jsx
> +export const Pagination = ({
Går ikke å eksportere denne som en function.

2023-03-02 06:27 UTC, tonystr commented on src/dashboard/components/table/addon/TablePagination.jsx
> +export const Pagination = ({
Hvorfor ikke? Husk at når noe eksporteres som default importeres det slik `import Pagination from...` istedenfor slik `import { Pagination } from...`. Filen burde forresten hete det samme som komponentet

2023-03-02 06:30 UTC, tonystr commented on src/dashboard/pages/texts/TextSinglePage.jsx
> +    });
Input kan hentes med e.target.value i onChange, da slipper vi å bruke ref. Da trenger vi heller ikke useEffect

2023-03-02 12:36 UTC, junus-sefa commented on src/dashboard/components/table/addon/TablePagination.jsx
> +export const Pagination = ({
![CleanShot 2023-03-02 at 13 35 41@2x](https://user-images.githubusercontent.com/72740756/222430699-af4241d0-a66e-4105-97a3-c495bd4892f8.jpg)
Får opp denne feilmeldingen.

2023-03-03 05:23 UTC, tonystr approved these changes
Veldig bra jobbet!

2023-03-03 14:00 UTC, merged